defmodule CompaniesRegEx.Repo.Migrations.NullablesRemoved do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:recruiters) do
      modify :about_us, :text, null: true
      modify :introduction, :text, null: true
    end
  end

  def down do
    alter table(:recruiters) do
      modify :introduction, :text, null: false
      modify :about_us, :text, null: false
    end
  end
end