defmodule CompaniesRegEx.Repo.Migrations.AddedLoc do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE EXTENSION IF NOT EXISTS  postgis")

    alter table(:recruiters) do
      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :content

      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      # remove :job_description

      add :location, :geometry
    end

    create table(:job_description, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :description, :text
      add :salary, :text
      add :type, :text

      add :recruiters_id,
          references(:recruiters,
            column: :id,
            name: "job_description_recruiters_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:job_description, "job_description_recruiters_id_fkey")

    drop table(:job_description)

    alter table(:recruiters) do
      remove :location
      # This is the `down` migration of the statement:
      #
      #     remove :job_description
      #

      # add :job_description, :text
      # This is the `down` migration of the statement:
      #
      #     remove :content
      #

      # add :content, :text
    end
  end
end
