defmodule CompaniesRegEx.Repo.Migrations.AddedDeveloper do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:developers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :name, :text, null: false
      add :website, :text
    end
  end

  def down do
    drop table(:developers)
  end
end