defmodule CompaniesRegEx.Resources.Developer do
  use Ash.Resource, data_layer: AshPostgres.DataLayer

  postgres do
    table "developers"
    repo CompaniesRegEx.Repo
  end

  code_interface do
    define_for CompaniesRegEx.Resources
    define :create, action: :create
    define :read_all, action: :read
    define :update, action: :update
    define :destroy, action: :destroy
    define :get_by_id, args: [:id], action: :by_id
  end

  actions do
    defaults [:create, :read, :update, :destroy]

    read :by_id do
      argument :id, :uuid, allow_nil?: false
      # Tells us we expect this action to return a single result
      get? true
      # marks it as a primary action
      # primary? true
      filter expr(id == ^arg(:id))
    end
  end

  attributes do
    # Add an autogenerated UUID primary key called `:id`.
    uuid_primary_key :id

    attribute :name, :string do
      allow_nil? false
    end

    attribute :website, :string do
      # allow_nil? false
    end

    # todo add location
    # attribute :lives_in,
  end
end
